const UserActionTypes = {
  GOOGLE_SIGNIN_START :'GOOGLE_SIGNIN_START',
  GOOGLE_SIGNIN_FAILURE :'GOOGLE_SIGNIN_FAILURE',
  GOOGLE_SIGNIN_SUCCESS :'GOOGLE_SIGNIN_SUCCESS'
}

export default UserActionTypes;